version: '3'
services:
  storefront:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: npm run dev
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - /app/.next
      - ./:/src
    networks:
      - storefront_network

networks:
  storefront_network:
    name: storefront_network
